version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: linkedinzup/api
    ports:
      - '8080:8080'
    environment:
      - PROFILE=dev
    links:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booking
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
    - 9000:8080